---

version: '3.8'

x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile
  tty: true
  stdin_open: true
  environment:
    PRODUCTION_DATABASE_USRENAME: postgres
    PRODUCTION_DATABASE_PASSWORD: postgres

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    <<: *app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - 3000:3000
