source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.4"

gem "rails", "~> 7.1.3"

gem "active_model_serializers"

gem 'pagy', '~> 8.6.2'

gem "pg", "~> 1.5"

gem "puma", "~> 6.4"

gem 'pundit', '~> 2.3'

gem "jbuilder"

gem "redis", "~> 5.2"

gem "figaro"

# gem "kredis"
gem 'jwt'

gem "bcrypt", "~> 3.1.20"

gem 'interactor'

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false

# gem "image_processing", "~> 1.2"

gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem 'annotate'
  gem "spring"
end

