default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] || device_mesh_development %>
  username: <%= ENV['DB_USERNAME'] || postgresql %>
  password: <%= ENV['DB_PASSWORD'] || postgresql %>
  host: <%= ENV['DB_HOST'] || localhost %>
  port: <%= ENV['DB_PORT'] || 5432 %>

development:
  <<: *default

test:
  <<: *default
  database: device_mesh_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || device_mesh_production %>
  username: <%= ENV['DB_USERNAME'] || postgresql %>
  password: <%= ENV['DB_PASSWORD'] || postgresql %>
  host: <%= ENV['DB_HOST'] || localhost %>
  port: <%= ENV['DB_PORT'] || 5432 %>
