name: Dependabot auto-merge

on:
  pull_request:
    # Trigger the workflow only for Dependabot-created pull requests
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '*'

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Approve the PR
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge the PR
        run: gh pr merge --auto --merge "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
