name: Build & Deploy Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: check docker
      run: docker -v
    
    - name: Build the Docker image
      run: docker compose --file ./docker-compose.yml build

    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Publish to DockerHub
      run: docker compose --file ./docker-compose.yml push
